"""PDF processing utilities: image conversion, text extraction, and evidence highlighting."""

from __future__ import annotations

import ast
import base64
import json
import os
import re
from collections import defaultdict

# Set PAPERLENS_DEBUG_HL=1 to print rect-locator outcomes per snippet to
# stdout.  Useful when the user reports "no highlights" — read the server
# logs and see exactly which snippets failed to locate.
_DEBUG_HL = 1

# Pattern that recognises table identifiers such as "Table 2", "TABLE A1",
# "Appendix Table 3", "Tabelle 4" (German), "Tableau 4" (French),
# "Tabla 4" (Spanish), "Tabella 4" (Italian), "Tabela 4" (Portuguese).
# We also accept the model's normalisation back to "TABLE N" even when the
# underlying PDF is non-English.
_TABLE_WORDS = ("table", "tbl", "tabelle", "tableau", "tabla", "tabella", "tabela")
_TABLE_REF_RE = re.compile(
    r"\b(?:appendix\s+)?(?:" + "|".join(_TABLE_WORDS) + r")\.?\s*([A-Z]?\d+(?:\.\d+)?)\b",
    re.IGNORECASE,
)

MAX_PAGES      = 40
EXTRACTION_DPI = 200   # high-res PNG sent to vision models
DISPLAY_DPI    = 144   # JPEG resolution for the browser viewer

# Per-page char threshold below which we consider a page "scanned" (no
# usable text layer).  Same constant used by pdf_to_pages_with_rects so the
# upfront probe and the post-extraction highlight detection agree.
_SCANNED_PAGE_CHAR_THRESHOLD = 50


# Fraction of the page area that a single image must cover for the page
# to be classified as a scan (with or without an OCR text layer overlaid).
# Empirical sweet spot: typical journal-scan PDFs have a single image at
# ~99 % page coverage; native text PDFs with embedded figures top out
# around 40-50 % even for full-page diagrams.
_SCANNED_IMAGE_AREA_THRESHOLD = 0.7


def _largest_image_fraction(page) -> float:
    """Return the largest image's bounding-box area as a fraction of the
    page area.  0.0 if the page has no images.  Used to detect scans that
    have had OCR run on top of them — those PDFs *do* have a text layer
    (so the old char-count heuristic misses them) but are still
    fundamentally raster scans of the original pages."""
    page_area = page.rect.width * page.rect.height
    if page_area <= 0:
        return 0.0
    largest = 0.0
    try:
        import fitz  # PyMuPDF
        for info in page.get_image_info(xrefs=True):
            bbox = info.get("bbox")
            if not bbox:
                continue
            try:
                rect = fitz.Rect(bbox)
            except Exception:
                continue
            frac = (rect.width * rect.height) / page_area
            if frac > largest:
                largest = frac
    except Exception:
        pass
    return largest


def _is_scanned_page(page) -> bool:
    """Return True for pages that are scans — either no usable text layer
    (empty / near-empty) OR a near-full-page image (typical of OCR'd
    scans where the text layer is machine-generated and overlaid on top
    of a raster).  This is the single source of truth for "is this page
    something the LLM should read visually rather than via text
    extraction"; both ``probe_text_layer`` and ``pdf_to_pages_with_rects``
    call into it so they always agree."""
    chars = len(page.get_text("text").strip())
    if chars < _SCANNED_PAGE_CHAR_THRESHOLD:
        return True
    return _largest_image_fraction(page) >= _SCANNED_IMAGE_AREA_THRESHOLD


def probe_text_layer(pdf_bytes: bytes) -> dict:
    """Inspect a PDF's text layer + image structure to decide whether
    text-extraction will give meaningful results.

    Returns a small dict the client uses to set expectations BEFORE the
    extraction runs:

      ``total_pages``         number of pages (capped at MAX_PAGES)
      ``total_text_chars``    total text-layer characters across all pages
      ``page_dims_px``        per-page ``[width, height]`` in pixels at the
                              extraction DPI (EXTRACTION_DPI).  Derived from
                              the page's point size — no rendering needed —
                              so the client can compute an exact vision-mode
                              token estimate (the page image we'd send is a
                              deterministic render at this DPI).
      ``scanned_pages``       1-indexed pages classified as scans — either
                              the text layer is empty OR the page is
                              dominated by a single full-page image
                              (typical of OCR'd scans where the text
                              layer was generated by an OCR pass and
                              doesn't faithfully reflect the visual
                              content).  These pages get vision extraction
                              and may not produce reliable highlights.
      ``text_layer_present``  True when the majority of pages are *not*
                              scanned.  False indicates the document is
                              fundamentally a raster scan and should be
                              processed via vision instead of text.

    Cheap: just opens the PDF and reads the text-layer + image metadata
    — no rendering.
    """
    import fitz  # PyMuPDF

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    n          = min(len(doc), MAX_PAGES)
    scanned    = []
    total_chars = 0
    page_dims_px: list[list[int]] = []
    _dpi_scale = EXTRACTION_DPI / 72.0   # points → pixels at our render DPI
    for i in range(n):
        page = doc[i]
        chars = len(page.get_text("text").strip())
        total_chars += chars
        # Pixel dimensions of the image we WOULD render for vision mode —
        # derived from the page's point size, no rasterisation needed.
        rect = page.rect
        page_dims_px.append([
            max(1, round(rect.width  * _dpi_scale)),
            max(1, round(rect.height * _dpi_scale)),
        ])
        if _is_scanned_page(page):
            scanned.append(i + 1)
    doc.close()

    return {
        "total_pages":        n,
        "total_text_chars":   total_chars,
        "page_dims_px":       page_dims_px,
        "scanned_pages":      scanned,
        # "Text-readable" if more than half of the pages are not scans.
        "text_layer_present": n > 0 and len(scanned) <= n // 2,
    }


# ── Image conversion ──────────────────────────────────────────────────────────

def pdf_to_images(pdf_bytes: bytes, dpi: int = EXTRACTION_DPI, fmt: str = "png") -> list[str]:
    """Convert PDF bytes to a list of base64-encoded images, one per page.

    Args:
        dpi: Rendering resolution.
        fmt: "png" for lossless (vision model input) or "jpeg" for smaller display images.
    """
    import fitz  # PyMuPDF

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    images = []
    mat = fitz.Matrix(dpi / 72, dpi / 72)

    for page_num in range(min(len(doc), MAX_PAGES)):
        page = doc[page_num]
        pix = page.get_pixmap(matrix=mat)
        img_bytes = pix.tobytes("jpeg", jpg_quality=72) if fmt == "jpeg" else pix.tobytes("png")
        images.append(base64.b64encode(img_bytes).decode())

    doc.close()
    return images


# ── Text extraction (DeepSeek / text-only path) ───────────────────────────────

def pdf_to_markdown(pdf_bytes: bytes, max_pages: int = MAX_PAGES) -> tuple[str, int]:
    """Extract the text layer of a PDF and return it as labelled markdown sections.

    Uses PyMuPDF's built-in text extraction.  Works well for native text PDFs;
    scanned / image-only PDFs will produce little or no output.

    Returns:
        (markdown_text, page_count)
    """
    import fitz  # PyMuPDF

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    n = min(len(doc), max_pages)
    pages = []

    for i in range(n):
        page = doc[i]
        # get_text("markdown") is available in PyMuPDF ≥ 1.24; fall back to plain text.
        try:
            text = page.get_text("markdown")
        except (TypeError, Exception):
            text = page.get_text("text")
        pages.append(f"--- PDF page {i + 1} of {n} ---\n{text.strip()}")

    doc.close()
    return "\n\n".join(pages), n


# ── Evidence parsing ──────────────────────────────────────────────────────────

_ARITH_EXPR_RE = re.compile(
    # JSON value position: after `:`, `[`, or `,`, possibly with whitespace.
    r"(?<=[:\[,])"
    # A bare arithmetic expression — number then one or more (op number)
    # repeats.  Operators: + - * /.  No parens, no identifiers.
    r"(\s*-?\d+(?:\.\d+)?(?:\s*[*/+\-]\s*-?\d+(?:\.\d+)?)+)"
    # Terminator: comma, close-brace, close-bracket (with optional ws).
    r"(?=\s*[,}\]])"
)
_SAFE_AST_NODES = (
    ast.Expression, ast.BinOp, ast.UnaryOp,
    ast.Add, ast.Sub, ast.Mult, ast.Div,
    ast.USub, ast.UAdd, ast.Constant,
)


def _eval_arith_expressions(text: str) -> str:
    """Repair pass for model output that emits arithmetic in JSON value
    position (e.g. ``"female": 100 * 1383 / 2221``).  Strict JSON forbids
    expressions — they have to be pre-computed scalars — so we evaluate
    each arithmetic expression and substitute the literal result.

    Safety: the regex only matches numbers and basic operators (no
    identifiers, no parens, no function calls), AND we validate the
    parsed AST node-by-node before evaluating.  Anything that doesn't
    look like pure arithmetic is left alone.
    """
    def _repl(m: re.Match) -> str:
        # Strip leading/trailing whitespace so ast.parse doesn't read
        # the leading spaces as indentation (which raises
        # IndentationError before our safety walk runs).
        expr = m.group(1).strip()
        try:
            tree = ast.parse(expr, mode="eval")
            for node in ast.walk(tree):
                if not isinstance(node, _SAFE_AST_NODES):
                    return m.group(0)
                if isinstance(node, ast.Constant) and not isinstance(node.value, (int, float)):
                    return m.group(0)
            value = eval(  # noqa: S307 — validated AST, no builtins
                compile(tree, "<arith>", "eval"),
                {"__builtins__": {}},
                {},
            )
            if isinstance(value, (int, float)):
                return repr(value)
        except (SyntaxError, ValueError, ZeroDivisionError, OverflowError):
            pass
        return m.group(0)
    return _ARITH_EXPR_RE.sub(_repl, text)


def _parse_result_json(result_text: str):
    """Strip markdown fences and parse the model's JSON output.  Returns the
    parsed object or None if it can't be parsed.

    Tolerant of: code fences, preamble before the JSON, trailing text after
    the JSON, arithmetic expressions in value position (the model sometimes
    emits ``100 * x / y`` instead of evaluating it — we evaluate it for
    them), and mid-output truncation (we close open strings/containers and
    retry).  This lets us still surface partial evidence/data even when
    the model gets cut off mid-output.
    """
    text = result_text.strip()
    text = re.sub(r"^```(?:json)?\s*\n?", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\n?```\s*$", "", text)
    # First repair step: evaluate any arithmetic expressions the model
    # emitted in JSON value position.  Cheap and idempotent on
    # arithmetic-free output, so safe to run unconditionally.
    text = _eval_arith_expressions(text)
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Locate the first plausible JSON container start.
    starts = [i for i in (text.find("{"), text.find("[")) if i != -1]
    if not starts:
        return None
    candidate = text[min(starts):]

    # Try shrinking from the end — strips trailing prose.
    for end in range(len(candidate), 0, -1):
        if candidate[end - 1] not in "}]":
            continue
        try:
            return json.loads(candidate[:end])
        except json.JSONDecodeError:
            continue

    # Truncation repair: walk forward as a tiny JSON tokenizer.  Whenever we
    # observe a *complete value* (string, number/literal, or closed container),
    # remember the position + open-container stack.  At the end, truncate at
    # the last such position and append the missing closing brackets.
    stack: list[str] = []
    in_string = False
    escape = False
    expecting_value = False  # True at top level, after `:` in obj, or `[`/`,` in arr
    safe_cut = 0
    safe_stack: list[str] = []

    def mark_safe(pos: int) -> None:
        nonlocal safe_cut, safe_stack
        if stack:
            safe_cut = pos
            safe_stack = list(stack)

    i = 0
    n = len(candidate)
    while i < n:
        ch = candidate[i]
        if in_string:
            if escape:
                escape = False
            elif ch == "\\":
                escape = True
            elif ch == '"':
                in_string = False
                if expecting_value:
                    mark_safe(i + 1)
                    expecting_value = False
            i += 1
            continue
        if ch in " \t\n\r":
            i += 1
            continue
        if ch == '"':
            in_string = True
            i += 1
            continue
        if ch == "{":
            stack.append("}")
            expecting_value = False  # next token is a key
            i += 1
            continue
        if ch == "[":
            stack.append("]")
            expecting_value = True
            i += 1
            continue
        if ch in "}]":
            if stack and stack[-1] == ch:
                stack.pop()
            mark_safe(i + 1)
            expecting_value = False
            i += 1
            continue
        if ch == ":":
            expecting_value = True
            i += 1
            continue
        if ch == ",":
            mark_safe(i)  # safe to truncate *before* a dangling comma
            expecting_value = stack[-1:] == ["]"]
            i += 1
            continue
        # Number / true / false / null literal — consume until a structural char
        j = i
        while j < n and candidate[j] not in '{}[],:" \t\n\r':
            j += 1
        if expecting_value:
            mark_safe(j)
            expecting_value = False
        i = j

    if not safe_stack:
        return None
    repaired = candidate[:safe_cut].rstrip().rstrip(",").rstrip()
    repaired += "".join(reversed(safe_stack))
    try:
        return json.loads(repaired)
    except json.JSONDecodeError:
        return None


def extract_evidence_snippets(result_text: str) -> dict[int, list[str]]:
    """Parse a model JSON response and return {page_num: [snippets]}.

    Only includes entries that have BOTH a snippet AND a usable page number —
    these are the ones we can actually highlight in the PDF viewer.
    """
    parsed = _parse_result_json(result_text)
    if parsed is None:
        return {}

    snippets_by_page: dict[int, list[str]] = defaultdict(list)

    def recurse(obj: object) -> None:
        if isinstance(obj, dict):
            if "snippet" in obj and "page" in obj:
                snippet = obj.get("snippet") or ""
                raw_page = obj.get("page")
                if snippet and raw_page is not None:
                    try:
                        page_num = int(float(raw_page))
                        if page_num > 0:
                            snippets_by_page[page_num].append(str(snippet))
                    except (ValueError, TypeError):
                        pass
            for v in obj.values():
                recurse(v)
        elif isinstance(obj, list):
            for item in obj:
                recurse(item)

    recurse(parsed)
    return dict(snippets_by_page)


def count_evidence_entries(result_text: str) -> int:
    """Count every evidence-like entry that has a non-empty snippet, regardless
    of whether it carries a usable page number.

    This lets the frontend tell apart 'no evidence at all' (prompt issue) from
    'evidence returned but no pages were specified' (model issue).
    """
    parsed = _parse_result_json(result_text)
    if parsed is None:
        return 0
    n = 0

    def walk(obj):
        nonlocal n
        if isinstance(obj, dict):
            if obj.get("snippet"):
                n += 1
            for v in obj.values():
                walk(v)
        elif isinstance(obj, list):
            for x in obj:
                walk(x)

    walk(parsed)
    return n


def find_text_rects_on_page(
    pdf_bytes: bytes,
    page_1indexed: int,
    texts: list[str],
    dpi: int = DISPLAY_DPI,
) -> dict[str, list[list[float]]]:
    """Find rect coordinates for each ``text`` on the specified PDF page.

    Used by the on-demand click-to-jump UI: when the user clicks a cell
    value (e.g. ``"42.87"``) the viewer wants to outline every occurrence
    of that literal text on the currently-displayed PDF page.  Rects are
    returned in image-pixel coordinates (multiplied by ``dpi/72``) so
    the client can drop them straight into the SVG overlay's viewBox
    without further conversion.

    Returns a dict ``{text: [[x, y, w, h], ...]}``.  Texts not found
    on the page map to empty lists.  Searches the literal string first,
    then dehyphenated, then case-insensitive — same fallback ladder the
    snippet locator uses, so the two highlight layers agree on what
    counts as a hit.  Skips texts shorter than 2 chars (would match
    noise) and longer than 200 chars (treat as a snippet, not a value).
    """
    import fitz  # PyMuPDF

    out: dict[str, list[list[float]]] = {}
    if not texts:
        return out
    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    try:
        if page_1indexed < 1 or page_1indexed > len(doc):
            return {t: [] for t in texts}
        page = doc[page_1indexed - 1]
        scale = dpi / 72.0
        _DEHY = getattr(fitz, "TEXT_DEHYPHENATE", 0)
        seen: set[str] = set()
        for raw in texts:
            t = (raw or "").strip()
            if not t or len(t) < 2 or len(t) > 200 or t in seen:
                continue
            seen.add(t)
            rects = page.search_for(t)
            if not rects:
                try:
                    rects = page.search_for(t, flags=_DEHY)
                except Exception:
                    rects = []
            scaled: list[list[float]] = []
            for r in (rects or []):
                # PyMuPDF Rect → [x, y, w, h] in image pixels
                scaled.append([
                    round(r.x0 * scale, 2),
                    round(r.y0 * scale, 2),
                    round((r.x1 - r.x0) * scale, 2),
                    round((r.y1 - r.y0) * scale, 2),
                ])
            out[t] = scaled
    finally:
        doc.close()
    return out


def detect_journal_page_offset(
    pdf_bytes: bytes,
    snippets_by_page: dict[int, list[str]],
    max_search_pages: int = 200,
    max_samples: int = 12,
) -> int:
    """Detect the offset between journal page numbers (what the evidence
    claims) and PDF-internal page indices (what the renderer needs).

    Academic-journal PDFs often start at, say, journal page 134 (article
    spans 134-156) while the PDF file itself has internal pages 1-23.
    The evidence array carries journal page numbers, so the click-to-jump
    and the snippet-highlighter both fall off the end without remapping.

    Strategy: gather snippets across out-of-range claimed pages, sort
    longest-first (longer = more unique → less likely to false-match on
    a similar-looking phrase elsewhere), search each across all PDF
    pages, and **vote** on the resulting offset.  The most common
    offset wins.  Voting protects against single-snippet false matches
    like ``"Observations 20"`` landing on a figure caption mentioning
    "20 observations" instead of the actual results table.  Returns 0
    when every claimed page is already in range or no snippet can be
    located.
    """
    if not snippets_by_page:
        return 0
    import fitz  # PyMuPDF
    from collections import Counter

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    n_pdf_pages = len(doc)
    if not any(p > n_pdf_pages for p in snippets_by_page.keys()):
        return 0
    scan_limit = min(n_pdf_pages, max_search_pages)

    # Build (claimed_page, snippet) pairs from every out-of-range page,
    # sorted longest-snippet-first so distinctive text votes before
    # generic phrases.
    candidates: list[tuple[int, str]] = []
    for claimed_page, snippets in snippets_by_page.items():
        if claimed_page <= n_pdf_pages:
            continue
        for snippet in snippets:
            if snippet and len(snippet) >= 10:
                candidates.append((claimed_page, snippet))
    candidates.sort(key=lambda t: -len(t[1]))

    offsets: Counter = Counter()
    for claimed_page, snippet in candidates[:max_samples]:
        needle = _normalize_snippet(snippet)
        found_page = None
        for length in (180, 120, 80):
            candidate = needle[:length]
            if len(candidate) < 10:
                continue
            for page_num in range(scan_limit):
                page = doc[page_num]
                rects = page.search_for(candidate)
                if not rects:
                    try:
                        rects = page.search_for(candidate, flags=1)
                    except Exception:
                        pass
                if rects:
                    found_page = page_num + 1
                    break
            if found_page:
                break
        if found_page is not None:
            offsets[found_page - claimed_page] += 1

    if not offsets:
        return 0
    # If two offsets tie, prefer the one closer to zero (smaller absolute
    # offset) — academic PDFs rarely have large negative offsets that
    # overlap with a smaller plausible one.
    top = offsets.most_common()
    best_count = top[0][1]
    contenders = [off for off, count in top if count == best_count]
    return min(contenders, key=lambda o: abs(o))


def _orphan_snippets(result_text: str) -> list[str]:
    """Snippets emitted by the model that lack a usable page number.

    These can sometimes be recovered by searching the PDF text for them —
    see ``recover_orphan_pages`` below.
    """
    parsed = _parse_result_json(result_text)
    if parsed is None:
        return []
    out: list[str] = []

    def walk(obj):
        if isinstance(obj, dict):
            snip = obj.get("snippet")
            if snip:
                raw_page = obj.get("page")
                page_ok = False
                if raw_page is not None:
                    try:
                        page_ok = int(float(raw_page)) > 0
                    except (ValueError, TypeError):
                        page_ok = False
                if not page_ok:
                    out.append(str(snip))
            for v in obj.values():
                walk(v)
        elif isinstance(obj, list):
            for x in obj:
                walk(x)

    walk(parsed)
    return out


def _locate_snippet_page(doc, snippet: str) -> int | None:
    """Try to find which 1-indexed page a snippet appears on.

    Tries the full normalized snippet first, then progressively shorter
    prefixes — same fallback chain as ``pdf_to_highlighted_images`` so the
    odds of finding *something* are high even when the model paraphrased a bit.
    Returns the first matching page, or None.
    """
    norm = _normalize_snippet(snippet)
    for query in (norm, norm[:120], norm[:80], norm[:50]):
        if not query:
            continue
        for page_num in range(min(len(doc), MAX_PAGES)):
            page = doc[page_num]
            try:
                if page.search_for(query):
                    return page_num + 1
            except Exception:
                continue
    return None


def recover_orphan_pages(
    result_text: str, pdf_bytes: bytes,
) -> dict[int, list[str]]:
    """For every evidence snippet the model returned WITHOUT a page number,
    search the PDF for the snippet and assign it to the page where it was
    found.  Returns the same {page: [snippets]} shape as
    ``extract_evidence_snippets`` for easy merging.
    """
    orphans = _orphan_snippets(result_text)
    if not orphans:
        return {}

    import fitz  # PyMuPDF

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    out: dict[int, list[str]] = defaultdict(list)
    try:
        for snippet in orphans:
            page = _locate_snippet_page(doc, snippet)
            if page is not None:
                out[page].append(snippet)
    finally:
        doc.close()
    return dict(out)


def merge_snippet_dicts(*dicts: dict[int, list[str]]) -> dict[int, list[str]]:
    """Combine multiple {page: [snippets]} dicts; preserves insertion order
    and de-dupes within each page."""
    merged: dict[int, list[str]] = defaultdict(list)
    for d in dicts:
        for page, snippets in d.items():
            for s in snippets:
                if s not in merged[page]:
                    merged[page].append(s)
    return dict(merged)


# ── Highlighted display images ────────────────────────────────────────────────

def _normalize_snippet(text: str) -> str:
    """Normalize model-quoted text for better PDF text-layer matching.

    Replaces common Unicode characters that differ between model output and the
    PDF text layer: curly quotes, em/en dashes, ligatures, non-breaking spaces.
    Also collapses whitespace.
    """
    replacements = {
        "\u2013": "-", "\u2014": "-",       # en-dash, em-dash
        "\u2018": "'", "\u2019": "'",        # curly single quotes
        "\u201c": '"', "\u201d": '"',        # curly double quotes
        "\ufb01": "fi", "\ufb02": "fl",      # fi, fl ligatures
        "\ufb03": "ffi", "\ufb04": "ffl",    # ffi, ffl ligatures
        "\u00a0": " ",                       # non-breaking space
        "\u00ad": "",                        # soft hyphen
    }
    for src, dst in replacements.items():
        text = text.replace(src, dst)
    return " ".join(text.split())


_CAPTION_TEMPLATES = ("{w} {n}.", "{w} {n}:", "{w} {n} ", "{w}{n}.")
# Word forms covered (mixed case + uppercase variant for each).  Both English
# (Table) and the most common European-language equivalents are included so a
# German PDF with "Tabelle 4." still gets its caption located when the model
# emitted "TABLE 4." in evidence.
_CAPTION_WORDS = (
    "Table", "TABLE",
    "Tabelle", "TABELLE",
    "Tableau", "TABLEAU",
    "Tabla", "TABLA",
    "Tabella", "TABELLA",
    "Tabela", "TABELA",
)


def _snippet_candidates(norm: str):
    """Yield search candidates for ``norm`` in priority order, from most
    specific to most generic.

    Handles the common shapes that defeat exact ``page.search_for``:
      * leading numeric markers ("1. Mir ist..." → "Mir ist...")
      * trailing numeric loadings (".75" / "0.69" at end)
      * line-broken contiguous text (sentence and word-window slices)
    """
    seen: set[str] = set()

    def emit(s: str):
        s = s.strip(" \t\n.,;:")
        if len(s) >= 6 and s not in seen:
            seen.add(s)
            return s
        return None

    cand = emit(norm)
    if cand: yield cand

    # Strip leading "12. " / "12) " markers.
    stripped_lead = re.sub(r"^\s*\d+[.\)]\s+", "", norm)
    cand = emit(stripped_lead)
    if cand: yield cand

    # Strip trailing numeric loadings: " .75", " 0.69", " -.42"
    stripped_tail = re.sub(r"\s+-?\.?\d+(?:[.,]\d+)?\s*$", "", stripped_lead)
    cand = emit(stripped_tail)
    if cand: yield cand

    # Length-based truncations on the cleaned string
    base = stripped_tail or stripped_lead or norm
    for n in (180, 120, 80):
        if len(base) > n:
            cand = emit(base[:n])
            if cand: yield cand

    # Sentence-style splits, longest first
    sentences = sorted(
        (s.strip() for s in re.split(r"(?<=[.!?])\s+", base) if len(s.strip()) >= 20),
        key=len, reverse=True,
    )
    for s in sentences:
        cand = emit(s)
        if cand: yield cand

    # Sliding word window — try larger windows first so we get the most
    # context (and the most unique match) before falling back to short ones.
    words = base.split()
    for size in (10, 8, 6, 4):
        if size > len(words):
            continue
        for i in range(len(words) - size + 1):
            cand = emit(" ".join(words[i : i + size]))
            if cand: yield cand


def _find_table_caption(page, table_num: str):
    """Locate the caption rect for 'Table N' on the page, if present.

    The model often cites a table from body text ("...presented in Table 1.").
    Searching for the snippet alone anchors the highlight in the prose, not the
    table.  Looking up the caption directly lets us expand from the table's
    actual top edge.  Returns the first match's rect, or None.

    Multilingual: tries Table / Tabelle / Tableau / Tabla / Tabella / Tabela
    captions so a German or other-language PDF still resolves correctly when
    the model normalised the table name to "TABLE N" in evidence.
    """
    for word in _CAPTION_WORDS:
        for tpl in _CAPTION_TEMPLATES:
            rects = page.search_for(tpl.format(w=word, n=table_num))
            if rects:
                return rects[0]
    return None


def _expand_to_table_region(page, anchor_rects: list) -> list | None:
    """Given highlight rects for a table caption/header, try to expand them to
    cover the full table body.

    Strategy: find the bounding box of the anchor rects, then collect all text
    blocks below it (within the same column band).  Stop when any of:
      * vertical gap > 2.5 × the running average row height,
      * the block looks like a new section heading (short all-caps / "Note"),
      * the block looks like prose (many words, few digits, much taller than
        a typical table row),
      * we've already eaten more than ~80 % of the page height below the
        caption (safety cap so a tightly-packed table followed by
        Discussion text never sweeps the whole column).

    Returns a list of fitz.Rect covering the expanded region, or None if
    expansion is not possible.
    """
    import fitz  # PyMuPDF

    if not anchor_rects:
        return None

    # Union of anchor rects
    anchor_union = anchor_rects[0]
    for r in anchor_rects[1:]:
        anchor_union = anchor_union | r

    # Gather all text blocks on the page
    blocks = page.get_text("blocks")  # (x0, y0, x1, y1, text, block_no, block_type)
    if not blocks:
        return None

    # Filter to blocks whose top edge is at or below the anchor's bottom
    below = [b for b in blocks if b[1] >= anchor_union.y1 - 2]
    if not below:
        return None
    # Sort top-to-bottom
    below.sort(key=lambda b: b[1])

    # Hard safety cap: never expand past ~80 % of the remaining page height.
    page_rect       = page.rect
    page_height     = page_rect.y1 - page_rect.y0
    remaining_below = page_rect.y1 - anchor_union.y1
    max_expand_y    = anchor_union.y1 + min(remaining_below * 0.80,
                                            page_height * 0.65)

    # Seed avg row height from the first few blocks below.
    seed        = below[:8]
    avg_height  = sum(b[3] - b[1] for b in seed) / max(len(seed), 1)
    table_rects: list = list(anchor_rects)
    prev_bottom = anchor_union.y1
    row_heights: list[float] = []

    def _looks_like_prose(text: str) -> bool:
        """Heuristic: long block of running prose (many words, few digits,
        contains terminal punctuation).  Tables almost never look this way
        even when tightly packed."""
        words = text.split()
        if len(words) < 25:
            return False
        digit_chars = sum(1 for c in text if c.isdigit())
        digit_frac  = digit_chars / max(len(text), 1)
        if digit_frac > 0.05:
            return False
        # Sentences end with . ! ? — prose usually has at least a couple.
        sentence_terminators = sum(text.count(c) for c in ".!?")
        return sentence_terminators >= 2

    for b in below:
        gap   = b[1] - prev_bottom
        text  = b[4].strip()
        block_height = b[3] - b[1]
        # Hard cap on cumulative expansion height.
        if b[3] > max_expand_y:
            break
        # Stop on large gap (new section).
        if gap > max(avg_height * 2.5, 20):
            break
        # New-section / "Note" heading.
        words = text.split()
        if len(words) <= 6 and (text == text.upper() or text.startswith("Note")):
            break
        # Block much taller than typical accumulated rows → likely a
        # paragraph below the table.
        if row_heights:
            row_heights_sorted = sorted(row_heights)
            median_h = row_heights_sorted[len(row_heights_sorted) // 2]
            if block_height > max(median_h * 4.0, 36) and len(words) >= 20:
                break
        # Prose-block detector (catches tightly-spaced Discussion text).
        if _looks_like_prose(text):
            break
        table_rects.append(fitz.Rect(b[0], b[1], b[2], b[3]))
        row_heights.append(block_height)
        prev_bottom = b[3]

    if len(table_rects) <= len(anchor_rects):
        return None  # no expansion happened

    return table_rects


def pdf_to_highlighted_images(
    pdf_bytes: bytes,
    snippets_by_page: dict[int, list[str]],
    dpi: int = DISPLAY_DPI,
) -> list[str]:
    """Render display-resolution JPEG images with evidence snippets highlighted.

    Uses PyMuPDF's text search to locate each snippet on its page and draws a
    yellow highlight annotation over it.  When the snippet references a table
    (e.g. "Table 2"), attempts to expand the highlight to cover the full table body.
    Falls back gracefully when text cannot be found.
    """
    import fitz  # PyMuPDF

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    images = []
    mat = fitz.Matrix(dpi / 72, dpi / 72)

    for page_num in range(min(len(doc), MAX_PAGES)):
        page = doc[page_num]
        page_1indexed = page_num + 1

        for snippet in snippets_by_page.get(page_1indexed, []):
            if len(snippet) < 5:
                continue
            norm = _normalize_snippet(snippet)
            is_table_ref = bool(_TABLE_REF_RE.search(norm))

            def _search(text: str) -> list:
                rects = page.search_for(text)
                if not rects:
                    try:
                        rects = page.search_for(text, flags=1)
                    except Exception:
                        pass
                return rects or []

            rects = (
                _search(norm)
                or _search(norm[:120])
                or _search(norm[:80])
            )
            if not rects:
                sentences = [
                    s.strip() for s in re.split(r"(?<=[.!?])\s+", norm)
                    if len(s.strip()) >= 20
                ]
                for sent in sentences:
                    rects = _search(sent)
                    if rects:
                        break
            if not rects:
                words = norm.split()
                for i in range(max(0, len(words) - 3)):
                    chunk = " ".join(words[i : i + 4])
                    rects = _search(chunk)
                    if rects:
                        break

            # If the snippet cites a table, try to highlight the full table
            # by locating its caption on the page (anchor of last resort).
            table_rects: list = []
            if is_table_ref:
                m = _TABLE_REF_RE.search(norm)
                if m:
                    caption = _find_table_caption(page, m.group(1))
                    if caption:
                        expanded = _expand_to_table_region(page, [caption])
                        table_rects = expanded if expanded else [caption]

            if rects:
                # Snippet text was found.  If we also found the table caption,
                # highlight both so the user sees the source quote AND the table
                # it refers to.  Otherwise expand around the snippet itself.
                if table_rects:
                    rects = list(rects) + list(table_rects)
                elif is_table_ref:
                    expanded = _expand_to_table_region(page, list(rects))
                    if expanded:
                        rects = expanded
            elif table_rects:
                # Snippet not found in the text, but we located the table by name.
                rects = table_rects

            if rects:
                try:
                    annot = page.add_highlight_annot(rects)
                    annot.update()
                except Exception:
                    pass

        pix = page.get_pixmap(matrix=mat)
        img_bytes = pix.tobytes("jpeg", jpg_quality=85)
        images.append(base64.b64encode(img_bytes).decode())

    doc.close()
    return images


def pdf_to_pages_with_rects(
    pdf_bytes: bytes,
    evidence_items: list[dict],
    dpi: int = DISPLAY_DPI,
) -> tuple[list[str], list[dict], list[int]]:
    """Render plain JPEG page images PLUS rect metadata for each evidence
    entry's location, so the client can overlay highlights selectively
    (filtered by the active sub-view).

    ``evidence_items`` is a list of dicts ``{page, snippet, field, source}``.
    ``page`` is 1-indexed.

    Returns:
        pages         — base64-encoded JPEG strings, one per PDF page
        highlights    — list of dicts with keys:
                        ``page``    1-indexed PDF page
                        ``snippet`` original snippet text (for tooltips)
                        ``field``   JSON path declared by the model
                        ``source``  table/figure id or None
                        ``rects``   list of [x, y, w, h] in image-pixel coords
        scanned_pages — 1-indexed pages whose text layer is essentially empty
                        (image-only / scanned).  These can't be highlighted —
                        ``page.search_for`` matches against the text layer,
                        which is what the locator (and any future fallback)
                        depends on.  The client uses this to display an
                        explanatory notice instead of a confusing empty
                        overlay.

    Memory-friendly alternative to ``pdf_to_highlighted_images``: we render
    each page only once (no per-sub-view duplication) and the client decides
    which rects to draw on top.
    """
    import fitz  # PyMuPDF
    _DEHY = getattr(fitz, "TEXT_DEHYPHENATE", 0)

    doc = fitz.open(stream=pdf_bytes, filetype="pdf")
    pages: list[str]       = []
    highlights: list[dict] = []
    scanned_pages: list[int] = []

    mat   = fitz.Matrix(dpi / 72, dpi / 72)
    scale = dpi / 72.0  # PDF points → image pixels

    # Group evidence items by page for one-pass rendering
    by_page: dict[int, list[dict]] = {}
    for ev in evidence_items:
        page = ev.get("page")
        if not isinstance(page, int) or page < 1:
            continue
        by_page.setdefault(page, []).append(ev)

    for page_idx in range(min(len(doc), MAX_PAGES)):
        page      = doc[page_idx]
        page_1idx = page_idx + 1

        # Detect scanned pages — either no usable text layer at all OR a
        # near-full-page image (the latter catches OCR'd scans where a
        # text layer was generated post-hoc and doesn't faithfully match
        # the visual content).  Same helper that ``probe_text_layer``
        # uses, so the upfront probe and the post-extraction notice
        # always agree.
        if _is_scanned_page(page):
            scanned_pages.append(page_1idx)
            if _DEBUG_HL:
                chars = len(page.get_text("text").strip())
                frac  = _largest_image_fraction(page)
                kind  = "no text layer" if chars < _SCANNED_PAGE_CHAR_THRESHOLD else \
                        f"image-dominated ({frac:.0%} of page)"
                print(f"[hl] p{page_1idx}: scanned ({kind}) — highlights may be unreliable", flush=True)

        for ev in by_page.get(page_1idx, []):
            snippet = ev.get("snippet") or ""
            if not snippet or len(snippet) < 5:
                continue
            norm         = _normalize_snippet(snippet)
            is_table_ref = bool(_TABLE_REF_RE.search(norm))

            def _search(text: str) -> list:
                # First pass: plain search.  Second pass: dehyphenated, which
                # also helps when the PDF text spans hyphenated line breaks
                # ("Hauptkomponenten-\nanalyse" → "Hauptkomponentenanalyse").
                rects = page.search_for(text) or []
                if not rects and _DEHY:
                    try:
                        rects = page.search_for(text, flags=_DEHY) or []
                    except Exception:
                        pass
                return rects

            rects: list = []
            matched_via: str | None = None
            for cand in _snippet_candidates(norm):
                rects = _search(cand)
                if rects:
                    matched_via = cand
                    break

            if _DEBUG_HL:
                tag = f"p{page_1idx} field={ev.get('field')!r}"
                if rects:
                    print(f"[hl] FOUND  {tag} via {matched_via[:60]!r} -> {len(rects)} rect(s)", flush=True)
                else:
                    print(f"[hl] MISS   {tag} snippet={norm[:80]!r}", flush=True)

            # Optional table-region expansion
            table_rects: list = []
            if is_table_ref:
                m = _TABLE_REF_RE.search(norm)
                if m:
                    caption = _find_table_caption(page, m.group(1))
                    if _DEBUG_HL:
                        print(f"[hl] table-ref t={m.group(1)!r} caption={'YES' if caption else 'no'} on p{page_1idx}", flush=True)
                    if caption:
                        expanded = _expand_to_table_region(page, [caption])
                        table_rects = expanded if expanded else [caption]

            if rects:
                if table_rects:
                    rects = list(rects) + list(table_rects)
                elif is_table_ref:
                    expanded = _expand_to_table_region(page, list(rects))
                    if expanded:
                        rects = expanded
            elif table_rects:
                rects = table_rects

            if rects:
                pixel_rects = [
                    [r.x0 * scale, r.y0 * scale,
                     (r.x1 - r.x0) * scale, (r.y1 - r.y0) * scale]
                    for r in rects
                ]
                highlights.append({
                    "page":    page_1idx,
                    "snippet": snippet,
                    "field":   ev.get("field"),
                    "source":  ev.get("source"),
                    "rects":   pixel_rects,
                })

        # Render this page WITHOUT highlight annotations
        pix       = page.get_pixmap(matrix=mat)
        img_bytes = pix.tobytes("jpeg", jpg_quality=85)
        pages.append(base64.b64encode(img_bytes).decode())

    if _DEBUG_HL:
        print(
            f"[hl] summary: {len(evidence_items)} evidence items -> "
            f"{len(highlights)} highlight rects, {len(pages)} pages rendered, "
            f"{len(scanned_pages)} scanned page(s): {scanned_pages}",
            flush=True,
        )

    doc.close()
    return pages, highlights, scanned_pages


def evidence_items_from_result(result_text: str) -> list[dict]:
    """Walk the parsed JSON and return every evidence-like entry that has a
    snippet AND a usable page number, preserving ``field`` and ``source``.

    This is the structured input to ``pdf_to_pages_with_rects``.
    """
    parsed = _parse_result_json(result_text)
    if parsed is None:
        return []
    out: list[dict] = []

    def walk(obj):
        if isinstance(obj, dict):
            snip = obj.get("snippet")
            page = obj.get("page")
            if snip and page is not None:
                try:
                    page_num = int(float(page))
                    if page_num > 0:
                        out.append({
                            "page":    page_num,
                            "snippet": str(snip),
                            "field":   obj.get("field"),
                            "source":  obj.get("source"),
                        })
                except (TypeError, ValueError):
                    pass
            for v in obj.values():
                walk(v)
        elif isinstance(obj, list):
            for x in obj:
                walk(x)

    walk(parsed)
    return out
